package com.dousnl.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-06-08T10:52:53.339+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://server.webservice.dousnl.com/", name = "Greeting")
@XmlSeeAlso({ObjectFactory.class})
public interface Greeting {

    @WebMethod
    @RequestWrapper(localName = "getAllUser", targetNamespace = "http://server.webservice.dousnl.com/", className = "com.dousnl.webservice.client.GetAllUser")
    @ResponseWrapper(localName = "getAllUserResponse", targetNamespace = "http://server.webservice.dousnl.com/", className = "com.dousnl.webservice.client.GetAllUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.dousnl.webservice.client.User> getAllUser();

    @WebMethod
    @RequestWrapper(localName = "greeting", targetNamespace = "http://server.webservice.dousnl.com/", className = "com.dousnl.webservice.client.Greeting_Type")
    @ResponseWrapper(localName = "greetingResponse", targetNamespace = "http://server.webservice.dousnl.com/", className = "com.dousnl.webservice.client.GreetingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String greeting(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
