
package org.dousnl.webservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-06-08T10:52:53.292+08:00
 * Generated source version: 3.1.8
 * 
 */
public final class Greeting_GreetingImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.webservice.dousnl.com/", "GreetingImplService");

    private Greeting_GreetingImplPort_Client() {
    }

    /*public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GreetingImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GreetingImplService ss = new GreetingImplService(wsdlURL, SERVICE_NAME);
        Greeting port = ss.getGreetingImplPort();  
        
        {
        System.out.println("Invoking getAllUser...");
        java.util.List<org.dousnl.webservice.client.User> _getAllUser__return = port.getAllUser();
        System.out.println("getAllUser.result=" + _getAllUser__return);


        }
        {
        System.out.println("Invoking greeting...");
        java.lang.String _greeting_arg0 = "";
        java.lang.String _greeting__return = port.greeting(_greeting_arg0);
        System.out.println("greeting.result=" + _greeting__return);


        }

        System.exit(0);
    }*/

}
